### ISSUE TITLE
error trying to convert to pdf

### ISSUE THREAD

**Issue by CRAG666** [boltlessengineer/norg-pandoc#1]
command  pandoc --from=init.lua todo.norg --output=todo.pdf

Error:
Error producing PDF.
! Package soul Error: Reconstruction failed.

See the soul package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.93 ...local when converting multiple files -- (}

**Comment by boltlessengineer** [comment]
Thank you for noticing me.
This is highly WIP project, so there can be some issues. Sorry, I forgot to mention it in README.

**Comment by boltlessengineer** [comment]
This is working fine from bdb19d0. Closing the issue
